default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: dpg-d6420nvfte5s73fsn8ug-a.oregon-postgres.render.com
  port: 5432
  username: drwise_admin_db_user
  password: Pp8oA9j9IXD22lbOyQQS5S6kZ4mf6SAJ

development:
  <<: *default
  database: drwise_admin_db

test:
  <<: *default
  database: drwise_admin_db_test

production:
  primary:
    <<: *default
    database: drwise_admin_db

  cable:
    <<: *default
    database: drwise_admin_db

  queue:
    <<: *default
    database: drwise_admin_db

  cache:
    <<: *default
    database: drwise_admin_db