default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: dpg-d5f0h3juibrs7391pjog-a.oregon-postgres.render.com
  port: 5432
  username: dhanvantari_farm_user
  password: pgY343DQx4wfkDUnLJScdnqkTxmV6H8t

development:
  <<: *default
  database: dhanvantari_farm

test:
  <<: *default
  database: dhanvantari_farm_test

production:
  primary:
    <<: *default
    database: dhanvantari_farm

  cable:
    <<: *default
    database: dhanvantari_farm

  queue:
    <<: *default
    database: dhanvantari_farm

  cache:
    <<: *default
    database: dhanvantari_farm