default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV['DB_HOST'] || 'dpg-d6g3ivv5r7bs73f87p1g-a.oregon-postgres.render.com' %>
  database: <%= ENV['DB_NAME'] || 'atmanirbhar_farm' %>
  username: <%= ENV['DB_USERNAME'] || 'atmanirbhar_farm_user' %>
  password: <%= ENV['DB_PASSWORD'] || 'jpp5Jf7vOzFm2ZA8ML2ThEbZIttRxNS1' %>
  port: <%= ENV['DB_PORT'] || 5432 %>

test:
  <<: *default
  database: atmanirbhar_farm_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  host: <%= ENV['DB_HOST'] || 'dpg-d6g3ivv5r7bs73f87p1g-a' %>
  database: <%= ENV['DB_NAME'] || 'atmanirbhar_farm' %>
  username: <%= ENV['DB_USERNAME'] || 'atmanirbhar_farm_user' %>
  password: <%= ENV['DB_PASSWORD'] || 'jpp5Jf7vOzFm2ZA8ML2ThEbZIttRxNS1' %>
  port: <%= ENV['DB_PORT'] || 5432 %>